apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployments/
  - services/
  - configmaps/
  - secrets/
  - ingress/

commonLabels:
  app: mealkitz
  environment: base

namespace: mealkitz

configMapGenerator:
  - name: app-config
    literals:
      - APP_ENV=production
      - LOG_LEVEL=info
      - ENABLE_METRICS=true

secretGenerator:
  - name: app-secrets
    files:
      - secrets/supabase.env
      - secrets/twilio.env
      - secrets/google-maps.env

images:
  - name: mealkitz/api
    newTag: latest
  - name: mealkitz/worker
    newTag: latest
  - name: mealkitz/web
    newTag: latest 