apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealkitz-api
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mealkitz-api
  template:
    metadata:
      labels:
        app: mealkitz-api
    spec:
      containers:
      - name: api
        image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: mealkitz-secrets
              key: database-url
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5 